public class OrderExtension {

	public OrderExtension( ApexPages.StandardController( Order theOrder ) {}

    public void buildOrderItems() {}
    public void OnFieldChange() {}
    public void SelectFamily() {}
    public void Save() {}
    public void First() {}
    public void Last() {}
    public void GetHasNext() {}
    public void GetHasPrevious() {}
    public void GetPageNumber() {}
    public void GetTotalPages() {}
    public void GetFamilyOptions() {}
    
}